import React, { useCallback, useEffect, useState } from 'react';
import classNames from 'classnames/bind';
import { useHistory, useParams } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { isEmpty } from 'lodash';

import { useModal } from '../../contexts';
import { Icons, Layout, Routes } from '../../constants';
import { useEntityMissing } from '../../hooks';
import { IMediaPicture, IMediaPlaylistTrack } from '../../interfaces';
import { RootState } from '../../reducers';
import { I18nService, MediaCollectionService, MediaPlaylistService } from '../../services';

import {
  MediaCollectionActions,
  MediaCoverPictureUploadable,
  MediaPlaylistDeleteTracksModal,
  MediaTrackContextMenuItem,
  MediaTrackList,
  TextClamp,
} from '../../components';

import styles from './playlist.component.css';

const cx = classNames.bind(styles);

export function PlaylistPage() {
  const { playlistId } = useParams() as { playlistId: string };
  const history = useHistory();
  const mediaSelectedPlaylist = useSelector((state: RootState) => state.mediaLibrary.mediaSelectedPlaylist);
  const [mediaPlaylistTracks, setMediaPlaylistTracks] = useState<IMediaPlaylistTrack[]>([]);
  const isPlaylistRemoved = useEntityMissing(mediaSelectedPlaylist);
  const { showModal } = useModal();

  useEffect(() => {
    MediaPlaylistService.loadMediaPlaylist(playlistId);

    return () => MediaPlaylistService.unloadMediaPlaylist();
  }, [
    playlistId,
  ]);

  useEffect(() => {
    if (!mediaSelectedPlaylist) {
      return;
    }

    MediaPlaylistService.resolveMediaPlaylistTracks(mediaSelectedPlaylist.id)
      .then((tracks) => {
        setMediaPlaylistTracks(tracks);
      });
  }, [
    mediaSelectedPlaylist,
  ]);

  useEffect(() => {
    if (isPlaylistRemoved) {
      history.replace(Routes.LibraryPlaylists);
    }
  }, [isPlaylistRemoved, history]);

  const handleMediaTracksSorted = useCallback(async (mediaTracks: IMediaPlaylistTrack[]) => {
    if (!mediaSelectedPlaylist) {
      return;
    }

    await MediaPlaylistService.updateMediaPlaylist(mediaSelectedPlaylist.id, {
      tracks: mediaTracks,
    });

    setMediaPlaylistTracks(mediaTracks);
  }, [
    mediaSelectedPlaylist,
  ]);

  const handleSelectionDelete = useCallback((mediaPlaylistId: string, mediaPlaylistTrackIds: string[]) => new Promise<boolean>((resolve) => {
    showModal(MediaPlaylistDeleteTracksModal, {
      mediaPlaylistId,
      mediaPlaylistTrackIds,
    }, {
      onComplete: (res) => {
        // success signal if selected were deleted
        resolve(!isEmpty(res?.deletedPlaylistTrackIds));
      },
    });
  }), [
    showModal,
  ]);

  const handleOnPictureUpdate = useCallback(async (picture: IMediaPicture) => {
    if (!mediaSelectedPlaylist) {
      return;
    }

    await MediaPlaylistService.updateMediaPlaylist(mediaSelectedPlaylist.id, {
      cover_picture: picture,
    });
  }, [
    mediaSelectedPlaylist,
  ]);

  if (!mediaSelectedPlaylist || isPlaylistRemoved) {
    return null;
  }

  const isAutoGeneratedPlaylist = !!mediaSelectedPlaylist.is_auto_generated;

  return (
    <div className="container-fluid">
      <div className={cx('playlist-header')}>
        <div className="row">
          <div className={cx(Layout.Grid.CollectionHeaderCoverColumn, 'playlist-header-cover-column')}>
            {isAutoGeneratedPlaylist
              ? (
                <MediaCoverPictureUploadable
                  mediaPicture={mediaSelectedPlaylist.cover_picture}
                  mediaPictureAltText={mediaSelectedPlaylist.name}
                  className={cx('playlist-cover-picture')}
                  mediaCoverPlaceholderIcon={Icons.PlaylistPlaceholder}
                />
              )
              : (
                <MediaCoverPictureUploadable
                  mediaPicture={mediaSelectedPlaylist.cover_picture}
                  mediaPictureAltText={mediaSelectedPlaylist.name}
                  className={cx('playlist-cover-picture')}
                  onPictureUpdate={handleOnPictureUpdate}
                  mediaCoverPlaceholderIcon={Icons.PlaylistPlaceholder}
                />
              )}
          </div>
          <div className={cx(Layout.Grid.CollectionHeaderInfoColumn, 'playlist-header-info-column')}>
            <div className={cx('playlist-header-label')}>
              {I18nService.getString('label_playlist_header')}
            </div>
            <div className={cx('playlist-header-name')}>
              <TextClamp>
                {mediaSelectedPlaylist.name}
              </TextClamp>
            </div>
          </div>
        </div>
      </div>
      <div className={cx('playlist-actions')}>
        <MediaCollectionActions
          mediaItem={MediaCollectionService.getMediaItemFromPlaylist(mediaSelectedPlaylist)}
          hasTracks={!isEmpty(mediaPlaylistTracks)}
        />
      </div>
      {isEmpty(mediaPlaylistTracks) && (
        <div className="row">
          <div className="col-12">
            <div className={cx('playlist-empty-section')}>
              <div className={cx('playlist-empty-label')}>
                {I18nService.getString('label_playlist_empty')}
              </div>
            </div>
          </div>
        </div>
      )}
      {!isEmpty(mediaPlaylistTracks) && (
        <div className={cx('playlist-tracklist')}>
          <MediaTrackList
            sortable={!isAutoGeneratedPlaylist}
            mediaTracks={mediaPlaylistTracks}
            mediaTrackList={{
              id: mediaSelectedPlaylist.id,
            }}
            getMediaTrackId={mediaPlaylistTrack => mediaPlaylistTrack.playlist_track_id}
            contextMenuItems={[
              MediaTrackContextMenuItem.Like,
              MediaTrackContextMenuItem.AddToQueue,
              ...(!isAutoGeneratedPlaylist ? [MediaTrackContextMenuItem.RemoveFromPlaylist] : []),
            ]}
            onMediaTracksSorted={!isAutoGeneratedPlaylist ? handleMediaTracksSorted : undefined}
            onSelectionDelete={!isAutoGeneratedPlaylist ? mediaTrackIds => handleSelectionDelete(mediaSelectedPlaylist.id, mediaTrackIds) : undefined}
          />
        </div>
      )}
    </div>
  );
}
